artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/shivakumar-ravichandran/ml-datasets/raw/refs/heads/main/Asteriod-impact-prediction/asteriod_dataset.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_transform:
  root_dir: model
  file_name: preprocessor.pkl

save_model:
  root_dir: model
  file_name: model.pkl